apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-storage
  namespace: n8n
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/n8n"
  volumeName: n8n-storage
